version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: asyncstandup-postgres
    environment:
      POSTGRES_DB: asyncstandup_dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword # Use a more secure password in real scenarios
    ports:
      - "5433:5432" # Expose on 5433 locally to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d asyncstandup_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: asyncstandup-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
